export const surahImageMap: { [key: number]: string } = {
  1: 'Al-Fatihah.svg',
  2: 'Al-Baqara.svg',
  3: 'Al Imran.svg',
  4: 'An-Nisa.svg',
  5: "Al-Ma'ida.svg",
  6: "Al-An'am.svg",
  7: "Al-A'raf.svg",
  8: 'Al-Anfal.svg',
  9: 'At-Tawba.svg',
  10: 'Yunus.svg',
  11: 'Hud.svg',
  12: 'Yusuf.svg',
  13: "Ar-Ra'd.svg",
  14: 'Ibrahim.svg',
  15: 'Al-Hijr.svg',
  16: 'An-Nahl.svg',
  17: 'Al-Isra.svg',
  18: 'Al-Kahf.svg',
  19: 'Maryam.svg',
  20: 'Taha.svg',
  21: 'Al-Anbiya.svg',
  22: 'Al-Hajj.svg',
  23: "Al-Mu'minoon.svg",
  24: 'An-Nur.svg',
  25: 'Al-Furqan.svg',
  26: "Ash-Shu'ara.svg",
  27: 'An-Naml.svg',
  28: 'Al-Qasas.svg',
  29: 'Al-Ankabut.svg',
  30: 'Ar-Rum.svg',
  31: 'Luqman (surah).svg',
  32: 'As-Sajda.svg',
  33: 'Al-Ahzab.svg',
  34: 'Saba (surah).svg',
  35: 'Fatir (surah).svg',
  36: 'Ya-Sin.svg',
  37: 'As-Saaffat.svg',
  38: 'Sad (surah).svg',
  39: 'Az-Zumar.svg',
  40: 'Ghafir.svg',
  41: 'Fussilat.svg',
  42: 'Ash-Shura.svg',
  43: 'Az-Zukhruf.svg',
  44: 'Ad-Dukhan.svg',
  45: 'Al-Jathiya.svg',
  46: 'Al-Ahqaf.svg',
  47: 'Muhammad (surah).svg',
  48: 'Al-Fath.svg',
  49: 'Al-Hujurat.svg',
  50: 'Qaf (surah).svg',
  51: 'Adh-Dhariyat.svg',
  52: 'At-Tur.svg',
  53: 'An-Najm.svg',
  54: 'Al-Qamar.svg',
  55: 'Ar-Rahman.svg',
  56: "Al-Waqi'a.svg",
  57: 'Al-Hadid.svg',
  58: 'Al-Mujadila.svg',
  59: 'Al-Hashr.svg',
  60: 'Al-Mumtahanah.svg',
  61: 'As-Saff.svg',
  62: 'Al-Jumua.svg',
  63: 'Al-Munafiqun.svg',
  64: 'At-Taghabun.svg',
  65: 'At-Talaq.svg',
  66: 'At-Tahrim.svg',
  67: 'Al-Mulk.svg',
  68: 'Al-Qalam.svg',
  69: 'Al-Haaqqa.svg',
  70: 'Al-Maarij.svg',
  71: 'Nuh (surah).svg',
  72: 'Al-Jinn.svg',
  73: 'Al-Muzzammil.svg',
  74: 'Al-Muddathir.svg',
  75: 'Al-Qiyama.svg',
  76: 'Al-Insan.svg',
  77: 'Al-Mursalat.svg',
  78: 'An-Naba.svg',
  79: 'An-Naziat.svg',
  80: 'Abasa.svg',
  81: 'At-Takwir.svg',
  82: 'Al-Infitar.svg',
  83: 'Al-Mutaffifin.svg',
  84: 'Al-Inshiqaq.svg',
  85: 'Al-Burooj.svg',
  86: 'At-Tariq.svg',
  87: 'Al-Ala.svg',
  88: 'Al-Ghashiyah.svg',
  89: 'Al-Fajr (surah).svg',
  90: 'Al-Balad.svg',
  91: 'Ash-Shams.svg',
  92: 'Al-Lail.svg',
  93: 'Ad-Dhuha.svg',
  94: 'Al-Inshirah.svg',
  95: 'At-Tin.svg',
  96: 'Al-Alaq.svg',
  97: 'Al-Qadr.svg',
  98: 'Al-Bayyina.svg',
  99: 'Az-Zalzala.svg',
  100: 'Al-Adiyat.svg',
  101: 'Al-Qaria.svg',
  102: 'At-Takathur.svg',
  103: 'Al-Asr.svg',
  104: 'Al-Humaza.svg',
  105: 'Al-Fil.svg',
  106: 'Quraysh (surah).svg',
  107: "Al-Ma'un.svg",
  108: 'Al-Kawthar.svg',
  109: 'Al-Kafirun.svg',
  110: 'An-Nasr.svg',
  111: 'Al-Masad.svg',
  112: 'Al-Ikhlas.svg',
  113: 'Al-Falaq.svg',
  114: 'Al-Nas.svg',
};
