export { SettingsContent } from './SettingsContent';
export { default as SettingsSidebar } from './SettingsSidebar';
export { ReadingSettings } from './ReadingSettings';
export { FontSettings } from './FontSettings';
export { TranslationSettings } from './TranslationSettings';
export { TafsirSettings } from './TafsirSettings';
export { SettingsContentWrapper } from './SettingsContentWrapper';
export { SettingsPanels } from './SettingsPanels';
export { SettingsHeader } from './SettingsHeader';
export { SettingsTabs } from './SettingsTabs';
