// File: app/lib/data.ts

export const allSurahs = [
  { number: 1, name: 'Al-Fatihah', arabicName: 'ٱلْفَاتِحَة', verses: 7, meaning: 'The Opening' },
  { number: 2, name: 'Al-Baqarah', arabicName: 'ٱلْبَقَرَة', verses: 286, meaning: 'The Cow' },
  {
    number: 3,
    name: 'Aal-E-Imran',
    arabicName: 'آلِ عِمْرَان',
    verses: 200,
    meaning: 'Family of Imran',
  },
  { number: 4, name: 'An-Nisa', arabicName: 'ٱلنِّسَاء', verses: 176, meaning: 'The Women' },
  {
    number: 5,
    name: 'Al-Maidah',
    arabicName: 'ٱلْمَائِدَة',
    verses: 120,
    meaning: 'The Table Spread',
  },
  { number: 6, name: 'Al-Anam', arabicName: 'ٱلْأَنْعَام', verses: 165, meaning: 'The Cattle' },
  { number: 7, name: 'Al-Araf', arabicName: 'ٱلْأَعْرَاف', verses: 206, meaning: 'The Heights' },
  {
    number: 8,
    name: 'Al-Anfal',
    arabicName: 'ٱلْأَنْفَال',
    verses: 75,
    meaning: 'The Spoils of War',
  },
  {
    number: 9,
    name: 'At-Tawbah',
    arabicName: 'ٱلتَّوْبَة',
    verses: 129,
    meaning: 'The Repentance',
  },
  { number: 10, name: 'Yunus', arabicName: 'يُونُس', verses: 109, meaning: 'Jonah' },
  { number: 11, name: 'Hud', arabicName: 'هُود', verses: 123, meaning: 'Hud' },
  { number: 12, name: 'Yusuf', arabicName: 'يُوسُف', verses: 111, meaning: 'Joseph' },
  { number: 13, name: 'Ar-Rad', arabicName: 'ٱلرَّعْد', verses: 43, meaning: 'The Thunder' },
  { number: 14, name: 'Ibrahim', arabicName: 'إِبْرَاهِيم', verses: 52, meaning: 'Abraham' },
  { number: 15, name: 'Al-Hijr', arabicName: 'ٱلْحِجْر', verses: 99, meaning: 'The Rocky Tract' },
  { number: 16, name: 'An-Nahl', arabicName: 'ٱلنَّحْل', verses: 128, meaning: 'The Bee' },
  {
    number: 17,
    name: 'Al-Isra',
    arabicName: 'ٱلْإِسْرَاء',
    verses: 111,
    meaning: 'The Night Journey',
  },
  { number: 18, name: 'Al-Kahf', arabicName: 'ٱلْكَهْف', verses: 110, meaning: 'The Cave' },
  { number: 19, name: 'Maryam', arabicName: 'مَرْيَم', verses: 98, meaning: 'Mary' },
  { number: 20, name: 'Taha', arabicName: 'طه', verses: 135, meaning: 'Ta-Ha' },
  {
    number: 21,
    name: 'Al-Anbiya',
    arabicName: 'ٱلْأَنْبِيَاء',
    verses: 112,
    meaning: 'The Prophets',
  },
  { number: 22, name: 'Al-Hajj', arabicName: 'ٱلْحَجّ', verses: 78, meaning: 'The Pilgrimage' },
  {
    number: 23,
    name: 'Al-Muminun',
    arabicName: 'ٱلْمُؤْمِنُون',
    verses: 118,
    meaning: 'The Believers',
  },
  { number: 24, name: 'An-Nur', arabicName: 'ٱلنُّور', verses: 64, meaning: 'The Light' },
  {
    number: 25,
    name: 'Al-Furqan',
    arabicName: 'ٱلْفُرْقَان',
    verses: 77,
    meaning: 'The Criterion',
  },
  { number: 26, name: 'Ash-Shuara', arabicName: 'ٱلشُّعَرَاء', verses: 227, meaning: 'The Poets' },
  { number: 27, name: 'An-Naml', arabicName: 'ٱلنَّمْل', verses: 93, meaning: 'The Ant' },
  { number: 28, name: 'Al-Qasas', arabicName: 'ٱلْقَصَص', verses: 88, meaning: 'The Stories' },
  {
    number: 29,
    name: 'Al-Ankabut',
    arabicName: 'ٱلْعَنْكَبُوت',
    verses: 69,
    meaning: 'The Spider',
  },
  { number: 30, name: 'Ar-Rum', arabicName: 'ٱلرُّوم', verses: 60, meaning: 'The Romans' },
  { number: 31, name: 'Luqman', arabicName: 'لُقْمَان', verses: 34, meaning: 'Luqman' },
  {
    number: 32,
    name: 'As-Sajdah',
    arabicName: 'ٱلسَّجْدَة',
    verses: 30,
    meaning: 'The Prostration',
  },
  {
    number: 33,
    name: 'Al-Ahzab',
    arabicName: 'ٱلْأَحْزَاب',
    verses: 73,
    meaning: 'The Combined Forces',
  },
  { number: 34, name: 'Saba', arabicName: 'سَبَأ', verses: 54, meaning: 'Sheba' },
  { number: 35, name: 'Fatir', arabicName: 'فَاطِر', verses: 45, meaning: 'Originator' },
  { number: 36, name: 'Ya-Sin', arabicName: 'يس', verses: 83, meaning: 'Ya Sin' },
  {
    number: 37,
    name: 'As-Saffat',
    arabicName: 'ٱلصَّافَّات',
    verses: 182,
    meaning: 'Those who set the Ranks',
  },
  { number: 38, name: 'Sad', arabicName: 'ص', verses: 88, meaning: 'The Letter "Saad"' },
  { number: 39, name: 'Az-Zumar', arabicName: 'ٱلزُّمَر', verses: 75, meaning: 'The Troops' },
  { number: 40, name: 'Ghafir', arabicName: 'غَافِر', verses: 85, meaning: 'The Forgiver' },
  {
    number: 41,
    name: 'Fussilat',
    arabicName: 'فُصِّلَت',
    verses: 54,
    meaning: 'Explained in Detail',
  },
  {
    number: 42,
    name: 'Ash-Shura',
    arabicName: 'ٱلشُّورَىٰ',
    verses: 53,
    meaning: 'The Consultation',
  },
  {
    number: 43,
    name: 'Az-Zukhruf',
    arabicName: 'ٱلزُّخْرُف',
    verses: 89,
    meaning: 'The Ornaments of Gold',
  },
  { number: 44, name: 'Ad-Dukhan', arabicName: 'ٱلدُّخَان', verses: 59, meaning: 'The Smoke' },
  {
    number: 45,
    name: 'Al-Jathiyah',
    arabicName: 'ٱلْجَاثِيَة',
    verses: 37,
    meaning: 'The Crouching',
  },
  {
    number: 46,
    name: 'Al-Ahqaf',
    arabicName: 'ٱلْأَحْقَاف',
    verses: 35,
    meaning: 'The Wind-Curved Sandhills',
  },
  { number: 47, name: 'Muhammad', arabicName: 'مُحَمَّد', verses: 38, meaning: 'Muhammad' },
  { number: 48, name: 'Al-Fath', arabicName: 'ٱلْفَتْح', verses: 29, meaning: 'The Victory' },
  { number: 49, name: 'Al-Hujurat', arabicName: 'ٱلْحُجُرَات', verses: 18, meaning: 'The Rooms' },
  { number: 50, name: 'Qaf', arabicName: 'ق', verses: 45, meaning: 'The Letter "Qaf"' },
  {
    number: 51,
    name: 'Adh-Dhariyat',
    arabicName: 'ٱلذَّارِيَات',
    verses: 60,
    meaning: 'The Winnowing Winds',
  },
  { number: 52, name: 'At-Tur', arabicName: 'ٱلطُّور', verses: 49, meaning: 'The Mount' },
  { number: 53, name: 'An-Najm', arabicName: 'ٱلنَّجْم', verses: 62, meaning: 'The Star' },
  { number: 54, name: 'Al-Qamar', arabicName: 'ٱلْقَمَر', verses: 55, meaning: 'The Moon' },
  {
    number: 55,
    name: 'Ar-Rahman',
    arabicName: 'ٱلرَّحْمَٰن',
    verses: 78,
    meaning: 'The Most Merciful',
  },
  {
    number: 56,
    name: 'Al-Waqiah',
    arabicName: 'ٱلْوَاقِعَة',
    verses: 96,
    meaning: 'The Inevitable',
  },
  { number: 57, name: 'Al-Hadid', arabicName: 'ٱلْحَدِيد', verses: 29, meaning: 'The Iron' },
  {
    number: 58,
    name: 'Al-Mujadila',
    arabicName: 'ٱلْمُجَادِلَة',
    verses: 22,
    meaning: 'The Pleading Woman',
  },
  { number: 59, name: 'Al-Hashr', arabicName: 'ٱلْحَشْر', verses: 24, meaning: 'The Exile' },
  {
    number: 60,
    name: 'Al-Mumtahanah',
    arabicName: 'ٱلْمُمْتَحَنَة',
    verses: 13,
    meaning: 'She that is to be examined',
  },
  { number: 61, name: 'As-Saff', arabicName: 'ٱلصَّفّ', verses: 14, meaning: 'The Ranks' },
  {
    number: 62,
    name: 'Al-Jumuah',
    arabicName: 'ٱلْجُمُعَة',
    verses: 11,
    meaning: 'The Congregation, Friday',
  },
  {
    number: 63,
    name: 'Al-Munafiqun',
    arabicName: 'ٱلْمُنَافِقُون',
    verses: 11,
    meaning: 'The Hypocrites',
  },
  {
    number: 64,
    name: 'At-Taghabun',
    arabicName: 'ٱلتَّغَابُن',
    verses: 18,
    meaning: 'The Mutual Disillusion',
  },
  { number: 65, name: 'At-Talaq', arabicName: 'ٱلطَّلَاق', verses: 12, meaning: 'The Divorce' },
  {
    number: 66,
    name: 'At-Tahrim',
    arabicName: 'ٱلتَّحْرِيم',
    verses: 12,
    meaning: 'The Prohibition',
  },
  { number: 67, name: 'Al-Mulk', arabicName: 'ٱلْمُلْك', verses: 30, meaning: 'The Sovereignty' },
  { number: 68, name: 'Al-Qalam', arabicName: 'ٱلْقَلَم', verses: 52, meaning: 'The Pen' },
  { number: 69, name: 'Al-Haqqah', arabicName: 'ٱلْحَاقَّة', verses: 52, meaning: 'The Reality' },
  {
    number: 70,
    name: 'Al-Maarij',
    arabicName: 'ٱلْمَعَارِج',
    verses: 44,
    meaning: 'The Ascending Stairways',
  },
  { number: 71, name: 'Nuh', arabicName: 'نُوح', verses: 28, meaning: 'Noah' },
  { number: 72, name: 'Al-Jinn', arabicName: 'ٱلْجِنّ', verses: 28, meaning: 'The Jinn' },
  {
    number: 73,
    name: 'Al-Muzzammil',
    arabicName: 'ٱلْمُزَّمِّل',
    verses: 20,
    meaning: 'The Enshrouded One',
  },
  {
    number: 74,
    name: 'Al-Muddaththir',
    arabicName: 'ٱلْمُدَّثِّر',
    verses: 56,
    meaning: 'The Cloaked One',
  },
  {
    number: 75,
    name: 'Al-Qiyamah',
    arabicName: 'ٱلْقِيَامَة',
    verses: 40,
    meaning: 'The Resurrection',
  },
  { number: 76, name: 'Al-Insan', arabicName: 'ٱلْإِنْسَان', verses: 31, meaning: 'Man' },
  {
    number: 77,
    name: 'Al-Mursalat',
    arabicName: 'ٱلْمُرْسَلَات',
    verses: 50,
    meaning: 'The Emissaries',
  },
  { number: 78, name: 'An-Naba', arabicName: 'ٱلنَّبَأ', verses: 40, meaning: 'The Tidings' },
  {
    number: 79,
    name: 'An-Naziat',
    arabicName: 'ٱلنَّازِعَات',
    verses: 46,
    meaning: 'Those who drag forth',
  },
  { number: 80, name: 'Abasa', arabicName: 'عَبَسَ', verses: 42, meaning: 'He Frowned' },
  {
    number: 81,
    name: 'At-Takwir',
    arabicName: 'ٱلتَّكْوِير',
    verses: 29,
    meaning: 'The Overthrowing',
  },
  {
    number: 82,
    name: 'Al-Infitar',
    arabicName: 'ٱلْإِنْفِطَار',
    verses: 19,
    meaning: 'The Cleaving',
  },
  {
    number: 83,
    name: 'Al-Mutaffifin',
    arabicName: 'ٱلْمُطَفِّفِين',
    verses: 36,
    meaning: 'The Defrauding',
  },
  {
    number: 84,
    name: 'Al-Inshiqaq',
    arabicName: 'ٱلْإِنْشِقَاق',
    verses: 25,
    meaning: 'The Sundering',
  },
  {
    number: 85,
    name: 'Al-Buruj',
    arabicName: 'ٱلْبُرُوج',
    verses: 22,
    meaning: 'The Mansions of the Stars',
  },
  { number: 86, name: 'At-Tariq', arabicName: 'ٱلطَّارِق', verses: 17, meaning: 'The Nightcommer' },
  { number: 87, name: 'Al-Ala', arabicName: 'ٱلْأَعْلَىٰ', verses: 19, meaning: 'The Most High' },
  {
    number: 88,
    name: 'Al-Ghashiyah',
    arabicName: 'ٱلْغَاشِيَة',
    verses: 26,
    meaning: 'The Overwhelming',
  },
  { number: 89, name: 'Al-Fajr', arabicName: 'ٱلْفَجْر', verses: 30, meaning: 'The Dawn' },
  { number: 90, name: 'Al-Balad', arabicName: 'ٱلْبَلَد', verses: 20, meaning: 'The City' },
  { number: 91, name: 'Ash-Shams', arabicName: 'ٱلشَّمْس', verses: 15, meaning: 'The Sun' },
  { number: 92, name: 'Al-Layl', arabicName: 'ٱللَّيْل', verses: 21, meaning: 'The Night' },
  { number: 93, name: 'Ad-Duha', arabicName: 'ٱلضُّحَىٰ', verses: 11, meaning: 'The Forenoon' },
  { number: 94, name: 'Ash-Sharh', arabicName: 'ٱلشَّرْح', verses: 8, meaning: 'The Relief' },
  { number: 95, name: 'At-Tin', arabicName: 'ٱلتِّين', verses: 8, meaning: 'The Fig' },
  { number: 96, name: 'Al-Alaq', arabicName: 'ٱلْعَلَق', verses: 19, meaning: 'The Clot' },
  { number: 97, name: 'Al-Qadr', arabicName: 'ٱلْقَدْر', verses: 5, meaning: 'The Power' },
  {
    number: 98,
    name: 'Al-Bayyinah',
    arabicName: 'ٱلْبَيِّنَة',
    verses: 8,
    meaning: 'The Clear Proof',
  },
  {
    number: 99,
    name: 'Az-Zalzalah',
    arabicName: 'ٱلزَّلْزَلَة',
    verses: 8,
    meaning: 'The Earthquake',
  },
  {
    number: 100,
    name: 'Al-Adiyat',
    arabicName: 'ٱلْعَادِيَات',
    verses: 11,
    meaning: 'The Courser',
  },
  {
    number: 101,
    name: 'Al-Qariah',
    arabicName: 'ٱلْقَارِعَة',
    verses: 11,
    meaning: 'The Calamity',
  },
  {
    number: 102,
    name: 'At-Takathur',
    arabicName: 'ٱلتَّكَاثُر',
    verses: 8,
    meaning: 'The Piling Up',
  },
  { number: 103, name: 'Al-Asr', arabicName: 'ٱلْعَصْر', verses: 3, meaning: 'The Declining Day' },
  { number: 104, name: 'Al-Humazah', arabicName: 'ٱلْهُمَزَة', verses: 9, meaning: 'The Traducer' },
  { number: 105, name: 'Al-Fil', arabicName: 'ٱلْفِيل', verses: 5, meaning: 'The Elephant' },
  { number: 106, name: 'Quraysh', arabicName: 'قُرَيْش', verses: 4, meaning: 'Quraysh' },
  {
    number: 107,
    name: 'Al-Maun',
    arabicName: 'ٱلْمَاعُون',
    verses: 7,
    meaning: 'The Small Kindnesses',
  },
  {
    number: 108,
    name: 'Al-Kawthar',
    arabicName: 'ٱلْكَوْثَر',
    verses: 3,
    meaning: 'The Abundance',
  },
  {
    number: 109,
    name: 'Al-Kafirun',
    arabicName: 'ٱلْكَافِرُون',
    verses: 6,
    meaning: 'The Disbelievers',
  },
  {
    number: 110,
    name: 'An-Nasr',
    arabicName: 'ٱلنَّصْر',
    verses: 3,
    meaning: 'The Divine Support',
  },
  { number: 111, name: 'Al-Masad', arabicName: 'ٱلْمَسَد', verses: 5, meaning: 'The Palm Fiber' },
  {
    number: 112,
    name: 'Al-Ikhlas',
    arabicName: 'ٱلْإِخْلَاص',
    verses: 4,
    meaning: 'The Sincerity',
  },
  { number: 113, name: 'Al-Falaq', arabicName: 'ٱلْفَلَق', verses: 5, meaning: 'The Daybreak' },
  { number: 114, name: 'An-Nas', arabicName: 'ٱلنَّاس', verses: 6, meaning: 'Mankind' },
];

// In a real application, you would have a more detailed mapping.
export const allJuz = Array.from({ length: 30 }, (_, i) => ({
  number: i + 1,
  name: `Juz ${i + 1}`,
  surahRange: 'Al-Fatihah 1 - Al-Baqarah 141', // Example placeholder
}));
