export const LANGUAGE_CODES: Record<string, string> = {
  English: 'en',
  Urdu: 'ur',
  Bengali: 'bn',
  Turkish: 'tr',
  Spanish: 'es',
  French: 'fr',
  Bosnian: 'bs',
  Russian: 'ru',
  Malayalam: 'ml',
  Indonesian: 'id',
  Uzbek: 'uz',
  Dutch: 'nl',
  German: 'de',
  Tajik: 'tg',
  Tamil: 'ta',
  Japanese: 'ja',
  Italian: 'it',
  Vietnamese: 'vi',
  Chinese: 'zh',
  Albanian: 'sq',
  Persian: 'fa',
  Bulgarian: 'bg',
  Bambara: 'bm',
  Hausa: 'ha',
  Portuguese: 'pt',
  Romanian: 'ro',
  Hindi: 'hi',
  Swahili: 'sw',
  Kazakh: 'kk',
  Thai: 'th',
  Tagalog: 'tl',
  'Central Khmer': 'km',
  Assamese: 'as',
  Korean: 'ko',
  Somali: 'so',
  Azeri: 'az',
  Kurdish: 'ku',
  'Divehi, Dhivehi, Maldivian': 'dv',
  Malay: 'ms',
  Dari: 'prs',
  Amazigh: 'zgh',
  Amharic: 'am',
  Chechen: 'ce',
  Czech: 'cs',
  Finnish: 'fi',
  Gujarati: 'gu',
  Hebrew: 'he',
  Georgian: 'ka',
  Kannada: 'kn',
  Kashmiri: 'ks',
  Ganda: 'lg',
  Macedonian: 'mk',
  Marathi: 'mr',
  Maranao: 'mrn',
  Nepali: 'ne',
  Norwegian: 'no',
  Oromo: 'om',
  Polish: 'pl',
  Pashto: 'ps',
  Kinyarwanda: 'rw',
  Sindhi: 'sd',
  'Northern Sami': 'se',
  'Sinhala, Sinhalese': 'si',
  Serbian: 'sr',
  Swedish: 'sv',
  Telugu: 'te',
  Tatar: 'tt',
  'Uighur, Uyghur': 'ug',
  Ukrainian: 'uk',
  Yoruba: 'yo',
};
