export const LANGUAGE_CODES: Record<string, string> = {
  english: 'en',
  urdu: 'ur',
  bengali: 'bn',
  bangla: 'bn',
  turkish: 'tr',
  spanish: 'es',
  french: 'fr',
  bosnian: 'bs',
  russian: 'ru',
  malayalam: 'ml',
  indonesian: 'id',
  'bahasa indonesia': 'id',
  uzbek: 'uz',
  dutch: 'nl',
  german: 'de',
  tajik: 'tg',
  tamil: 'ta',
  japanese: 'ja',
  italian: 'it',
  vietnamese: 'vi',
  chinese: 'zh',
  albanian: 'sq',
  persian: 'fa',
  bulgarian: 'bg',
  bambara: 'bm',
  hausa: 'ha',
  portuguese: 'pt',
  romanian: 'ro',
  hindi: 'hi',
  swahili: 'sw',
  kazakh: 'kk',
  thai: 'th',
  tagalog: 'tl',
  'central khmer': 'km',
  assamese: 'as',
  korean: 'ko',
  somali: 'so',
  azeri: 'az',
  kurdish: 'ku',
  'divehi, dhivehi, maldivian': 'dv',
  malay: 'ms',
  dari: 'prs',
  amazigh: 'zgh',
  amharic: 'am',
  chechen: 'ce',
  czech: 'cs',
  finnish: 'fi',
  gujarati: 'gu',
  hebrew: 'he',
  georgian: 'ka',
  kannada: 'kn',
  kashmiri: 'ks',
  ganda: 'lg',
  macedonian: 'mk',
  marathi: 'mr',
  maranao: 'mrn',
  nepali: 'ne',
  norwegian: 'no',
  oromo: 'om',
  polish: 'pl',
  pashto: 'ps',
  kinyarwanda: 'rw',
  sindhi: 'sd',
  'northern sami': 'se',
  'sinhala, sinhalese': 'si',
  serbian: 'sr',
  swedish: 'sv',
  telugu: 'te',
  tatar: 'tt',
  'uighur, uyghur': 'ug',
  ukrainian: 'uk',
  yoruba: 'yo',
};
