name: Nightly Suite

on:
  schedule:
    - cron: '0 3 * * *' # Daily at 03:00 UTC
  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:
  tests-and-lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run nightly tests (unit+integration+ui)
        run: npm run test:nightly

      - name: Build application
        run: npm run build

      - name: Start application
        run: |
          npm start &
          sleep 10

      - name: Wait for application to be ready
        run: npx wait-on http://localhost:3000 --timeout 60000

      - name: Run Lighthouse report
        run: |
          npm install -g @lhci/cli@0.12.x
          lhci autorun || true

      - name: Upload Lighthouse report (if present)
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: ./**/lhr-*.json
          retention-days: 14

